version: '2'
services:
  db:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - 5432:5432